name: Run pre-commit checks

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  run-pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Pull CI Docker image
        run: docker pull ghcr.io/jansucan/diff-dd-ci:latest

      - uses: actions/checkout@v3

      - name: Build diff-dd
        # This is needed to create generated include files so cppcheck can find
        # them
        run: sh ./devel_tools/ci_container/run.sh make

      - name: Run pre-commit
        run: sh ./devel_tools/ci_container/run.sh pre-commit run --all-files
