name: Run pre-commit checks

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  run-pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Install cppcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y cppcheck

      - name: Run pre-commit
        run: pre-commit run --all-files
