name: Run tests

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Pull CI Docker image
        run: docker pull ghcr.io/jansucan/diff-dd-ci:latest

      - uses: actions/checkout@v3

      - name: Run tests
        run: sh ./devel_tools/ci_container/run.sh make test
